architecture: replication
auth:
  postgresPassword: "postgres123"
  database: "testdb"
  username: "testuser"
  password: "test123"
primary:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    size: 1Gi
readReplicas:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    size: 1Gi