architecture: replication
primary:
  service:
    type: LoadBalancer
  persistence:
    size: 5Gi
readReplicas:
  replicaCount: 2  
auth:
  username: "testuser"
  password: "test123"
  database: "testdb"
  replicationUsername: "repl_user"
  replicationPassword: "repl123"