architecture: standalone
primary:
  service:
    type: ClusterIP
  persistence:
    size: 5Gi
auth:
  username: "testuser"
  password: "test123"
  database: "testdb"
  replicationUsername: "repl_user"
  replicationPassword: "repl123"